server:
  port: 8081
  servlet:
    context-path: /emptyProject

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mysql?userUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      type: com.zaxxer.hikari.HikariDataSource
      minimun-idel: 5
      idle-timeout: 6000000
      maximum-pool-size: 20
      max-lifetime: 18000000
      connection-timeout: 6000
      connection-test-query: SELECT 1 FROM DUAL
  servlet:
    multipart:
      enabled: true
      location: files
      maxRequestSize: 10485760 # 10MB
      maxFileSize: 104857600 # 100MB
  http:
    multipart:
      maxRequestSize: 10485760 # 10MB
      maxFileSize: 104857600 # 100MB

mybatis:
  config-location: classpath:mybatis/sqlMapConfig.xml
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
    - classpath:mybatis/mapper/simple/*.xml
  type-aliases-package: com.spicis.model.dto.simple

redis:
  host: 10.17.50.137
  port: 6379
  password: null
  timeout: 3000
  maxTotal: 200
  minIdle: 100
  maxIdle: 100
  maxWaitMillis: 1200

caffeine:
  default: 1000,3600

param:
  mini-program:
    appId: xxxx
    secretId: xxxx
    url:

